### PR TITLE
Resolve Lenel Open Access driver build issues

### LINKED ISSUE #151: Lenel Open Access driver fails to compile
**Describe the bug**

Lenel Open Access driver fails to compile

**To Reproduce**

Run the spec runner, or attempt to compile the driver.

**Screenshots or a paste of terminal output**

[This CI run details the failure](https://travis-ci.com/github/PlaceOS/drivers/builds/224456891#L537)

<details>
<summary>Compilation output</summary>

```
In src/build.cr:8:1

 8 | {{ ("require \"../" + env("COMPILE_DRIVER") + "\"").id }}
     ^
Error: expanding macro


There was a problem expanding macro 'macro_140043267412304'

Called macro defined in src/build.cr:8:1

 8 | {{ ("require \"../" + env("COMPILE_DRIVER") + "\"").id }}

Which expanded to:

 > 1 | require "../drivers/lenel/open_access.cr"
Error: while requiring "../drivers/lenel/open_access.cr"


In drivers/lenel/open_access.cr:6:1

 6 | require "./open_access/client"
     ^
Error: while requiring "./open_access/client"


In drivers/lenel/open_access/client.cr:3:1

 3 | require "responsible"
     ^
Error: can't find file 'responsible'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

</details>

**Versions:**

- Crystal: v1.0.0
- `placeos-driver`: v5.0.10

### PR DESCRIPTION
**Pull request by kimburgess**
Re-adds a [dependency that was dropped](https://github.com/PlaceOS/drivers/commit/162631230c365b40c9ed40b3d46ce1b523196f33#diff-cbaa8062ee0fcfb5af8adfd98f69af4766b9ad5bb5e79158abe8da34f6fd7de0L64-L66).

Reverts semantically important changes introduced in #149.

Resolves #151.

### CODE REVIEW

**Comment by caspiano** [comment]
Looks good, but also I don't think those type changes are semantic, they are syntatactic

**Comment by caspiano** [comment]
@kimburgess https://carc.in/#/r/b0wb

**Review by caspiano — APPROVED** [review]

**Comment by kimburgess** [comment]
@caspiano they're only equivalent within the type grammar. When passing as an arg (which is [what's happening here](https://github.com/place-labs/responsible/blob/9b434ef62e43848e24bc183abcff424617699466/src/responsible/response.cr#L92)) one is an instance of a NamedTuple, the other is the type.

https://carc.in/#/r/b0xc

**Comment by caspiano** [comment]
Good to know!

**Pull request merged**
