### PR TITLE
fix(event attendance recorder): record people count

### PR DESCRIPTION
**Pull request by chillfox**

### CODE REVIEW

**Comment by chillfox** [comment]
Beware of the web console for log lines are in reverse order!

**Comment by chillfox** [comment]
```sh
Nil assertion failed (NilAssertionError)
  from /usr/lib/crystal/core/nil.cr:108:5 in 'not_nil!'
  from repositories/drivers/drivers/place/bookings/event_attendance_recorder.cr:79:26 in 'apply_new_state'
  from repositories/drivers/drivers/place/bookings/event_attendance_recorder.cr:74:5 in 'status_changed'
  from repositories/drivers/drivers/place/bookings/event_attendance_recorder.cr:4:1 in '->'
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/subscriptions/indirect_subscription.cr:10:15 in 'callback'
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/subscriptions.cr:105:19 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /usr/lib/crystal/core/fiber.cr:98:34 in '->'
  from ???
```

**Comment by chillfox** [comment]
```sh
12:49 PM, EventAttendanceRecorder_1, [DEBUG] apply_new_state current booking_id: , status: pending
12:49 PM, EventAttendanceRecorder_1, [DEBUG] #apply_new_state called with new_booking_id: , new_status: busy
```

**Review by stakach — APPROVED** [review]
LGTM

**Pull request merged**
