### PR TITLE
Add Webex bot drivers

### PR DESCRIPTION
**Pull request by grkek**

### CODE REVIEW

**Review by stakach — CHANGES_REQUESTED** [review]
As discussed, remove the custom websocket implementation
the websocket is established during class initialisation so no need for `on_open`

```
@socket = socket = Websocket.new
socket.on_message ...
socket.on_binary ...
socket.send message.to_json
socket.run
```

**Comment by stakach** [comment]
@grkek made the changes to the websocket
what else needs to happen with this one? is it ready for testing?

**Comment by grkek** [comment]
> @grkek made the changes to the websocket what else needs to happen with this one? is it ready for testing?

We need to add a command with which we will be able to register events, for example:

A booking event, a guest arriving event, etc.

**Review by stakach — APPROVED** [review]
LGTM

**Pull request merged**
