### PR TITLE
Add missing fields to the user model

### PR DESCRIPTION
**Pull request by Hamada92**
This PR adds some missing fields to the user model in floorsense.

### CODE REVIEW

**Review by w-le — APPROVED** [review]
the params aligns, apart from `privacy` which isn't in the floorsense docs (maybe it's new?)
https://apiguide.smartalock.com/#2b73222c-a86e-4cc2-8a12-d8d307adf3b1

Example Response from floorsense api
```
{
  "result": true,
  "type": "response",
  "info": {
    "email": "simon@amixcapital.com",
    "uid": "31344311",
    "usertype": "user",
    "pin": "8721",
    "name": "Simon Hope",
    "lastlogin": 1582692563,
    "expiry": 0,
    "extid": "9876543210987654321",
    "reslimit": 0,
    "uidtoken": "694433b85d6c7b2dd2c37c75a9c9a401",
    "desc": "#firstaid"
  }
}
```

**Comment by Hamada92** [comment]
Thanks @w-le  , if we keep the privacy one there, would it break anything?

**Comment by w-le** [comment]
yep I don't think it will break anything so I've approved the PR. We'll let @stakach review as well since he is much more familiar with this driver.

**Review by stakach — APPROVED** [review]
LGTM

**Pull request merged**
